---
title: "Clean cpue data"
author: "Max Lindmark"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
pdf_document: default
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 12,
  fig.asp = 0.618,
  fig.align ='center'
)
```

# Clean data and split by taxonomic group

## Load libraries
```{r libraries, message=FALSE}
# Load libraries, install if needed
library(tidyverse); theme_set(theme_classic())
library(readxl)
library(tidylog)
library(RCurl)
library(sp)
library(geosphere)
library(viridis)
library(RColorBrewer)
library(patchwork)
library(janitor)
library(icesDatras)
library(mapdata)
library(patchwork)
library(rgdal)
library(raster)
library(sf)
library(rgeos)
library(chron)
library(lattice)
library(ncdf4)
library(marmap)
library(rnaturalearth)
library(rnaturalearthdata)
library(mapplots)
library(qwraps2) # To load entire cache in interactive r session, do: qwraps2::lazyload_cache_dir(path = "saduria_index_cache/html")

# For adding maps to plots
world <- ne_countries(scale = "medium", returnclass = "sf")

# Specify map ranges
# ymin = 54; ymax = 58; xmin = 9.5; xmax = 22
ymin = 54; ymax = 58; xmin = 12.5; xmax = 22

# Make plot function
plot_map_raster <- function(dat, column = "est") {
  ggplot(dat, aes_string("X", "Y", fill = column)) +
    geom_raster() +
    facet_wrap(~year) +
    coord_fixed() +
    scale_fill_viridis_c() +
    geom_sf(data = world, inherit.aes = F, size = 0.2) +
    coord_sf(xlim = c(xmin, xmax), ylim = c(ymin, ymax))
}
```

## Read that data that we previously compiled:
  
```{r read data, message=FALSE, results="hide"}
d <- read.csv("data/data_complete.csv")
 
# Inspect
d %>% as.data.frame() %>% head()

# Filter years. Based in previous data exploration we will use data from 1984 and forward for now (when coverage roughly became what it is now)
d <- d %>% filter(artal > 1983)

################################################################################################
################
################
################
################
################
# FILTER MONTHS!!!

# Get a vector of the unique sampling ID's so that we can add them as 0's in the presence data
# First create the ID
d <- d %>%
  mutate(sample_id = paste(provID, artal, sep = "_"))

# Now get the unique IDs in a data frame
unique_samples <- d %>%
  mutate(sample_id = paste(provID, artal, sep = "_")) %>%
  distinct(sample_id)
```

## Add in oceanographic variables

## Split and clean data by taxonomic group:

### Saduria
```{r split and clean data by taxonomic group, message=FALSE, results="hide"}
# Filter the saduria data so that we get only hauls with saduria
sad <- d %>% filter(taxa == "Saduria entomon")

# Remove unique samples from the vector that are already in the saduria data
no_saduria_samples <- unique_samples$sample_id[!unique_samples$sample_id %in% unique(sad$sample_id)]
no_saduria_samples <- d %>%
  filter(sample_id %in% no_saduria_samples) %>%
  distinct(sample_id)

# Check again if these samples are in the saduria data (they shouldn't)
sad %>% filter(sample_id %in% c(no_saduria_samples$sample_id))

# Nope!

# Compare the lengths of the dataframes to ensure they sum up
length(unique(d$sample_id))
length(unique(no_saduria_samples$sample_id)) + length(unique(sad$sample_id))

# Good. Now add in these id's back to the saduria-only data
# First remove the coordinates from the saduria data. We will match the coordinates by ID from the full data to get all samples
sad <- sad %>% dplyr::select(-Latitud, -Longitud, -artal)

sad <- bind_rows(sad, no_saduria_samples)

# Now join in the coordinates and year column again:
coord_dat <- d %>% dplyr::select(Latitud, Longitud, sample_id, artal) %>% distinct(sample_id, .keep_all = TRUE)
sad <- left_join(sad, coord_dat, by = "sample_id")

# Clean up the data
colnames(sad)
str(sad)

sad <- sad %>%
  dplyr::select(antal, biomassa, djup, artal, datum, species_group, Latitud, Longitud,
                species_group, sample_id, provID) %>%
  rename("abundance" = "antal", "biomass" = "biomassa", "depth" = "djup", "year" = "artal",
         "date" = "datum", "lat" = "Latitud", "lon" = "Longitud")

# First, if there is an NA in abundance, it should be replaced with zero becomes it comes from the id's without saduria
sad <- sad %>% mutate(abundance = coalesce(abundance, 0L))

# We can see that they come from the non-saduria samples
# Filter saduria with 0 abundance. Are there any ID's that are not in the vector above?
# test <- sad %>% filter(abundance == 0)
# test$sample_id[!test$sample_id %in% unique_samples_saduria_absent$sample_id]

# Ok, check if there are any rows with biomass but no abundance
sad %>% filter(abundance == 0L) %>% distinct(biomass)
# Nope!

# Plot the distribution of abundance per sample_id
# How many rows do I have per sample_id?
sad %>% group_by(sample_id) %>% mutate(n = n()) %>% ungroup() %>% distinct(n)

# Good... Now plot the distribution of abundances
ggplot(sad, aes(abundance)) + geom_histogram()

# Probably some outliers! Check
sad %>% arrange(desc(abundance))

# Not sure, will keep but crop the plot

# Good... Now plot the distribution of abundances
ggplot(sad, aes(abundance)) + geom_histogram() + xlim(c(-1, 30))

# And the distribution of biomasses:
# First make the biomass column 0 if abundance is 0 - else NA (because info is missing)
sad <- sad %>% mutate(biomass = ifelse(abundance == 0, 0, biomass))

# How many NA biomass data? (only 69 rows..)
sad %>% drop_na(biomass)

# Good... Now plot the distribution of biomasses
ggplot(sad, aes(biomass)) + geom_histogram()

# Finally, save data
write.csv(sad, "data/for_analysis/saduria.csv")
```

### Amphipoda
### Mytilus
### Limecola baltica
### Polychaeta
### Cumacea
### Mysida
